common/urls.py
from django.urls import path
from . import views
app_name='common'
urlpatterns=[
    path('',views.home,name='index'),
    path('adminlogin',views.adminlogin,name='admin_login'),
    path('teacherlogin',views.teacherlogin,name='teacher_login'),
    path('studentlogin',views.studentlogin,name='student_login')
]

schoolERP/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('teacher/',include('teacher.urls')),
    path('student/',include('student.urls')),
    path('schooladmin/',include('schooladmin.urls')),
    path('',include('common.urls'))


]

schooladmin/urls.py
from django.urls import path
from . import views
app_name ='schooladmin'
urlpatterns=[
    path('home',views.schooladmin_home,name='sa_home'),
    path('addstudent',views.schooladmin_addstudent,name='sa_add'),
    path('viewstudent',views.schooladmin_viewstudent,name='sa_view'),
    path('attendance',views.schooladmin_viewattendance,name='sa_attendance'),
    path('example',views.schooladmin_master,name='sa_example')
]

student/urls.py
from django.urls import path
from . import views
app_name='student'
urlpatterns=[
    path('home',views.student_home,name='st_home'),
    path('changepswd',views.student_changepswd,name='st_chpswd'),
    path('profile',views.student_profile,name='st_profile'),
    path('attendance',views.student_attendance,name='attendance')
]

teacher/urls.py
from django.urls import path
from . import views
app_name='teacher'
urlpatterns=[
    path('home',views.teacher_home,name='tr_home'),
    path('viewstudent',views.teacher_studentview,name='tr_view'),
    path('profile',views.teacher_profile,name='tr_profile'),
    path('attendance',views.teacher_attendance,name='tr_attendance')
]

common/models.py
from django.db import models

# Create your models here.

schooladmin/models.py
from django.db import models

# Create your models here.

student/models.py
from django.db import models

# Create your models here.

teacher/models.py
from django.db import models

# Create your models here.

common/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request,'common/home.html')

def adminlogin(request):
    return render(request,'common/adminlogin.html')

def studentlogin(request):
    return render(request,'common/studentlogin.html')

def teacherlogin(request):
    return render(request,'common/teacherlogin.html')

schooladmin/views.py
from django.shortcuts import render

# Create your views here.

def schooladmin_home(request):
    return render(request,'schooladmin/home.html')

def schooladmin_addstudent(request):
    return render(request,'schooladmin/addstudent.html')

def schooladmin_viewstudent(request):
    return render(request,'schooladmin/viewstudent.html')

def schooladmin_viewattendance(request):
    return render(request,'schooladmin/attendance.html')

def schooladmin_master(request):
    return render(request,'schooladmin/example.html')


    

student/views.py
from django.shortcuts import render

# Create your views here.

def student_home(request):
    return render(request,'student/home.html')

def student_attendance(request):
    return render(request,'student/attendance.html')

def student_changepswd(request):
    return render(request,'student/changepswd.html')

def student_profile(request):
    return render(request,'student/profile.html')

    

teacher/views.py
from django.shortcuts import render

# Create your views here.

def teacher_home(request):
    return render(request,'teacher_templates/home.html')

def teacher_attendance(request):
    return render(request,'teacher_templates/attendance.html')

def teacher_studentview(request):
    return render(request,'teacher_templates/viewstudents.html')

def teacher_profile(request):
    return render(request,'teacher_templates/profile.html')

    

common/templates/common/adminlogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2 style="color:blueviolet">Welcome  admin </h2>
    <form action="{% url 'schooladmin:sa_home' %}">

    
    <table>
    <tr>
    <td>
    <label>UserName</label>
    <input type="text"><br/>
    </td>
    <tr>
    <td>
    <label>Password</label>&nbsp;&nbsp;
    <input type="password"><br/>
    </td>
</tr>
<tr>
    <td>
        <input type="submit" value="Submit"></input>
    </td>
</tr>
</table>
 </form>   
 <img src="{% static 'images/admis.jpg'%}"/>
</body>
</html>

common/templates/common/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 style="color:brown">Welcome to school</h1>
    <h2>You can choose your option here</h2>
    <a href="{% url 'common:admin_login' %}">schooladmin</a><br/>
    <a href="{% url 'common:teacher_login' %}">teacher login</a><br/>
    <a href="{% url 'common:student_login' %}">student login</a>
</body>
</html>

common/templates/common/studentlogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2 style="color:blueviolet">Welcome student</h2>
    <form action="{% url 'student:st_home' %}">
    <table>
    <tr>
    <td>
    <label>UserName</label>
    <input type="text"><br/>
    </td>
    <tr>
    <td>
    <label>Password</label>&nbsp;&nbsp;
    <input type="password"><br/>
    </td>
</tr>
<tr>
    <td>
        <input type="submit" value="Submit"></input>
    </td>
</tr>
</table>
  </form>  
</body>
</html>

common/templates/common/teacherlogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2 style="color:blueviolet">Welcome teacher</h2>
     <form action="{% url 'teacher:tr_home' %}">
    <table>
    <tr>
    <td>
    <label>UserName</label>
    <input type="text"><br/>
    </td>
    <tr>
    <td>
    <label>Password</label>&nbsp;&nbsp;
    <input type="password"><br/>
    </td>
</tr>
<tr>
    <td>
        <input type="submit" value="Submit"></input>
    </td>
</tr>
</table>
</form> 
</body>
</html>

schooladmin/templates/schooladmin/addstudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>You can add new students details here....</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus, quaerat eum, tempore non ullam nobis harum optio dolor aut mollitia placeat necessitatibus voluptatem fuga, vero labore! Sapiente dignissimos officia est!</p>
    <br/>
    <br/>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni rerum consequatur nostrum, possimus quidem laboriosam mollitia aspernatur temporibus corporis recusandae laudantium, fugit sunt commodi, ut veniam. Vitae sunt molestias repellendus?</p>
    <h1>updated</h1>
</body>
</html>

schooladmin/templates/schooladmin/attendance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Attendance details of the students are follows</h2>
<b>class 1A</b>
<table border="2">
    <tr>
        <th>Name</th>
        <th>%of Attendance</th>
    </tr>
    <tr>
        <td>Lorem.</td>
        <td>90</td>
    </tr>
    <tr>
        <td>Lorem.</td>
        <td>88</td>
    </tr>
    <tr>
        <td>Lorem.</td>
        <td>89</td>
    </tr>
    <tr>
        <td>Lorem.</td>
        <td>89</td>
    </tr>
    <tr>
        <td>Lorem.</td>
        <td>89</td>
    </tr>
    <tr>
        <td>Lorem.</td>
        <td>89</td>
    </tr>
    <tr>
        <td>Lorem.</td>
        <td>89</td>
    </tr>
</table>

</body>
</html>

schooladmin/templates/schooladmin/example.html
{% extends 'schooladmin/master.html' %}
{% block school %}Exampletitle{% endblock %}
{% block content %}
<div>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde quas placeat exercitationem, odit voluptate iure nemo quam mollitia excepturi aliquid quidem accusamus tempora esse amet incidunt dolor fugiat inventore labore?

    </p>
</div>

{% endblock %}

schooladmin/templates/schooladmin/home.html
{% extends 'schooladmin/master.html' %}
{% block school %}Exampletitle{% endblock %}
{% block content %}
<h1>Welcome admin</h1>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quia assumenda nisi nihil ut, quisquam dolorem ipsam consequuntur ab. Dolorem cumque veniam aut numquam quo enim qui fuga excepturi, architecto eum?</p>
    <br/>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore neque distinctio quas hic nobis aut nihil unde ipsum error molestias.</p>


{% endblock %}


   

schooladmin/templates/schooladmin/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block school %}{% endblock %}</title>
</head>
<body>
    <div>
    <h2>ABCD PUBLIC SCHOOL</h2>
    </div>
    {% block content %}{% endblock %}
    <div>
        <h3>This is footer</h3>
    </div>
</body>
</html>

schooladmin/templates/schooladmin/viewstudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>The details of your students are follows</h2>
    <table border="2">
        <tr>
            <th>class & division</th>
            
        </tr>
        <tr>
            <td>Lorem</td>
        </tr>
        <tr>
            <td>Lorem</td>
        </tr>
        <tr>
            <td>Lorem</td>
        </tr>
        <tr>
            <td>Lorem</td>
        </tr>

    </table>
</body>
</html>

student/templates/student/attendance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Hey students you can see your attendance here...</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus sit odit error quis, culpa dolore quia quos. Id minus ea, nesciunt, sed dicta ipsa natus pariatur et itaque doloribus ullam?</p>
    <br/>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero, non corrupti provident modi recusandae cupiditate sunt? Et nihil eum harum.</p>
    <h3>new student add here</h3>
</body>
</html>

student/templates/student/changepswd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hey student you can change your password here</h1>
    <label>old password</label>
    <input type="password"><br/>
    <br/>
    
    <label background-color="red">New password</label>
    <input type="password">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero nostrum numquam optio ratione doloribus commodi architecto. Rem nisi nihil repellendus pariatur quae exercitationem! Sint culpa consequatur nam, corrupti explicabo voluptas.</p>
</body>
</html>

student/templates/student/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hey students....Welcome to school</h1>
    <b>You can choose your options here..</b>
    <ul type="disc">
        <li>gffhgj</li>
        <li>fhgjh</li>
        <li>dfg</li>
        <li>fddgfjh</li>

    </ul>    

</body>
</html>

student/templates/student/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Students,you can see our profiles here</h1>
<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Autem incidunt deleniti facilis, alias beatae recusandae nesciunt minima dolor. Maiores atque itaque facilis a aspernatur tempore voluptates rem perspiciatis distinctio nisi.</p>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi omnis quia ea molestiae exercitationem minus dolorum veritatis similique temporibus minima et voluptatem laboriosam adipisci quidem pariatur odit, amet quaerat vel.</p>
<p>dgfjgjhkjkgdtfgjjjjjjjjjjjjjjjjjjjjjjgydrssssssssssssssssssfjhkjk
    dsfghhhjhkkhytdrew4367679800jhgcnhm,kllkhvkk
</p>
</body>
</html>

teacher/templates/teacher_templates/attendance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Please add your students attendance</h2>
    <table width="40%" border="2">
        <tr>
            <th>Name</th>
            <th>class</th>
            <th>Division</th>
        </tr>
        <tr>
            <td>dysgddgg</td>
            <td>2</td>
            <td>A</td>
        </tr>
        <tr>
            <td>dysgddgg</td>
            <td>2</td>
            <td>A</td>
        </tr>
        <tr>
            <td>dysgdgf</td>
            <td>2</td>
            <td>A</td>
        </tr>

    </table>
</body>
</html>

teacher/templates/teacher_templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome Teacher</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe quod necessitatibus ad dolorum libero magnam minima sunt aut, porro facilis veniam iure voluptates blanditiis recusandae earum, odio iste expedita dicta deleniti non soluta incidunt. Laudantium fuga dolorem quisquam maxime sed?</p>
</body>
</html>

teacher/templates/teacher_templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>List of the teachers in the school </h2>
    <ul>
        <li>Lorem, ipsum dolor.

        </li>
        <li>Lorem ipsum dolor sit.</li>
        <li>Lorem ipsum dolor sit.</li>
        <li>Lorem ipsum dolor sit.</li>
        <li>Lorem ipsum dolor sit.</li>
    </ul>
</body>
</html>

teacher/templates/teacher_templates/viewstudents.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>Your students are...</h3>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque quam debitis voluptatum corporis magni illum quia consequuntur incidunt, quas quos est hic itaque. Rem incidunt excepturi aperiam! Voluptate possimus amet tempore adipisci sapiente quam fugit, ab quia eveniet debitis at, quasi modi laudantium nemo ducimus officia expedita omnis similique nihil.</p>
</body>
</html>